### ISSUE TITLE
Unknown plugin "dynamic-import-node"

### ISSUE THREAD

**Issue by MikeTheCanuck** [MikeTheCanuck/hackoregon-frontend-starter#1]
Trying to build this project against TravisCI, and TravisCI is throwing this error during build:

`
2.77s$ npm test
> hackoregon-frontend-starter@0.1.0 test /home/travis/build/MikeTheCanuck/hackoregon-frontend-starter
> mocha --opts ./mocha.opts 'src/**/*.test.js'
/home/travis/build/MikeTheCanuck/hackoregon-frontend-starter/node_modules/babel-core/lib/transformation/file/options/option-manager.js:176
          throw new ReferenceError(messages.get("pluginUnknown", plugin, loc, i, dirname));
          ^
ReferenceError: Unknown plugin "dynamic-import-node" specified in "/home/travis/build/MikeTheCanuck/hackoregon-frontend-starter/.babelrc.env.test" at 1, attempted to resolve relative to "/home/travis/build/MikeTheCanuck/hackoregon-frontend-starter"
    at /home/travis/build/MikeTheCanuck/hackoregon-frontend-starter/node_modules/babel-core/lib/transformation/file/options/option-manager.js:176:17
    at Array.map (native)
    at Function.normalisePlugins (/home/travis/build/MikeTheCanuck/hackoregon-frontend-starter/node_modules/babel-core/lib/transformation/file/options/option-manager.js:154:20)
    at OptionManager.mergeOptions (/home/travis/build/MikeTheCanuck/hackoregon-frontend-starter/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:36)
    at OptionManager.init (/home/travis/build/MikeTheCanuck/hackoregon-frontend-starter/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at compile (/home/travis/build/MikeTheCanuck/hackoregon-frontend-starter/node_modules/babel-register/lib/node.js:103:45)
    at loader (/home/travis/build/MikeTheCanuck/hackoregon-frontend-starter/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/home/travis/build/MikeTheCanuck/hackoregon-frontend-starter/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /home/travis/build/MikeTheCanuck/hackoregon-frontend-starter/node_modules/mocha/lib/mocha.js:222:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/travis/build/MikeTheCanuck/hackoregon-frontend-starter/node_modules/mocha/lib/mocha.js:219:14)
    at Mocha.run (/home/travis/build/MikeTheCanuck/hackoregon-frontend-starter/node_modules/mocha/lib/mocha.js:487:10)
    at Object.<anonymous> (/home/travis/build/MikeTheCanuck/hackoregon-frontend-starter/node_modules/mocha/bin/_mocha:459:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
npm ERR! Test failed.  See above for more details.
The command "npm test" exited with 1.
cache.2
store build cache
0.00s
2.20schanges detected, packing new archive
uploading archive
Done. Your build exited with 1.
`

**Comment by MikeTheCanuck** [comment]
This appears to document how the issue arises:
https://www.npmjs.com/package/babel-plugin-dynamic-import-node

I noticed an errant trailing comma in .babelrc.  I'll push a commit without it and see if TravisCI still barfs.

**Comment by MikeTheCanuck** [comment]
Nope, no difference:
https://travis-ci.org/MikeTheCanuck/hackoregon-frontend-starter/jobs/196489107

**Comment by MikeTheCanuck** [comment]
Looking more closely, the babel-plugin documentation noted above discusses the installation of the plugin as well as usage.

Looking more closely at package.json, the devDependencies dictionary includes many other babel-plugin-* references but not this one.  I'll try adding it and see if that clears the issue.

**Comment by MikeTheCanuck** [comment]
seems we've defeated that error, only to be arrested by another similar one:

'2.46s$ npm test
> hackoregon-frontend-starter@0.1.0 test /home/travis/build/MikeTheCanuck/hackoregon-frontend-starter
> mocha --opts ./mocha.opts 'src/**/*.test.js'
module.js:440
    throw err;
    ^
Error: Cannot find module 'styled-components'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/travis/build/MikeTheCanuck/hackoregon-frontend-starter/src/components/App/index.js:5:1)
    at Module._compile (module.js:541:32)
    at loader (/home/travis/build/MikeTheCanuck/hackoregon-frontend-starter/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/travis/build/MikeTheCanuck/hackoregon-frontend-starter/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/travis/build/MikeTheCanuck/hackoregon-frontend-starter/src/components/App/index.test.js:3:1)
    at Module._compile (module.js:541:32)
    at loader (/home/travis/build/MikeTheCanuck/hackoregon-frontend-starter/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/travis/build/MikeTheCanuck/hackoregon-frontend-starter/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at /home/travis/build/MikeTheCanuck/hackoregon-frontend-starter/node_modules/mocha/lib/mocha.js:222:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/travis/build/MikeTheCanuck/hackoregon-frontend-starter/node_modules/mocha/lib/mocha.js:219:14)
    at Mocha.run (/home/travis/build/MikeTheCanuck/hackoregon-frontend-starter/node_modules/mocha/lib/mocha.js:487:10)
    at Object.<anonymous> (/home/travis/build/MikeTheCanuck/hackoregon-frontend-starter/node_modules/mocha/bin/_mocha:459:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:445:3
npm ERR! Test failed.  See above for more details.
The command "npm test" exited with 1.
cache.2
store build cache
0.00s
2.33schanges detected, packing new archive
uploading archive
Done. Your build exited with 1.
'

**Comment by MikeTheCanuck** [comment]
I jammed "styled-components": "1.4.2" into the devDependencies dictionary because I found a similar package "style-loader" there as well, and no "style*" packages anywhere in the dependencies dictionary.

**Comment by MikeTheCanuck** [comment]
!!!

> The command "npm test" exited with 0.

https://travis-ci.org/MikeTheCanuck/hackoregon-frontend-starter/jobs/196490922

That it failed to deploy at the end is irrelevant to my investigation here - this gives me confidence that we have a workable S3 deploy for static files (HTML, CSS, JS).  Tracking down the source of the following error will be interesting to David and his team I'd guess, and I'd be happy to help with that if needed:

> /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-core-2.7.3/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': The request signature we calculated does not match the signature you provided. Check your key and signing method. (Aws::S3::Errors::SignatureDoesNotMatch)

**Comment by MikeTheCanuck** [comment]
On second thought, this "SignatureDoesNotMatch" issue definitely looks like a devops issue:
https://github.com/travis-ci/travis-ci/issues/4776
https://github.com/aws/aws-sdk-ruby/issues/965

It appears that TravisCI is pulling in the latest version of aws-sdk-* (2.7.3), and it further appears that travis-ci has no single definitive solution to this issue.  I'm going to ask other devops teammates to try and see if they're able to get further than me.

**Comment by MikeTheCanuck** [comment]
I have regenerated my signature (travis encrypt...) and I get the same error trace back from TravisCI.  Going to need some independent verification of this one.

**Comment by DavideDaniel** [comment]
dynamic import isn't needed currently and should be removed from this fork - or just merge in the recent changes

**Comment by MikeTheCanuck** [comment]
Let's consider this issue closed at this point.
